name: Kloia Case CI Pipeline 

on:
  push:
    branches: ["main"] # main branch'e gelen her committe tetiklenir
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    strategy:
      fail-fast: false
      matrix:
        service: [
          adservice,
          cartservice,
          checkoutservice,
          currencyservice,
          emailservice,
          frontend,
          loadgenerator,
          paymentservice,
          productcatalogservice,
          recommendationservice,
          shippingservice
        ]
    
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3
      
      - name: AWS Kimlik Dogrulamasi
        uses: aws-actions/configure-aws-credentials@v2
        with: #oidc
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Amazon ECR'a Giris Yap
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build ve Push 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sock-shop/${{ matrix.service }} # her servis kendi kendi ecr reposuna
          IMAGE_TAG: ${{ github.sha }} 
        run: |
          SERVICE_PATH="./src/${{ matrix.service }}"
          echo "Islem yapilan servis: $SERVICE_PATH "

          # varsayilan 
          BUILD_CONTEXT="$SERVICE_PATH"
          DOCKERFILE_PATH="$SERVICE_PATH/Dockerfile"

          # cartservice ozel ayarlari
          if [ "${{ matrix.service }}" == "cartservice" ]; then
            echo "cartservice yolu! "
            DOCKERFILE_PATH="$SERVICE_PATH/src/Dockerfile"
            BUILD_CONTEXT="$SERVICE_PATH/src"
          fi

          echo "Build Context: $BUILD_CONTEXT"
          echo "Dockerfile: $DOCKERFILE_PATH"

          #build
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_PATH $BUILD_CONTEXT
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f $DOCKERFILE_PATH $BUILD_CONTEXT

          #push
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          echo "basariyla tamamlandi: $ECR_REPOSITORY"
  
  update-helm-values:
    needs: build-and-push #build bitmeden çalışma
    runs-on: ubuntu-latest
    permissions:
      contents: write # Git'e yazmak için gerekli izin
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main # Guncel branch'i cek

      - name: Helm Values Guncelle (GitOps Trigger)
        run: |
          git config --global user.email "ci-bot@kloia.com"
          git config --global user.name "CI Bot"
          
          # values.yaml dosyasinda tag'i güncelle
          VALUES_FILE="./helm-chart/values.yaml"
          NEW_TAG="${{ github.sha }}"
          
          yq -i ".images.tag = \"$NEW_TAG\"" $VALUES_FILE
          
          if [[ -n $(git status -s) ]]; then
            git add $VALUES_FILE
            git commit -m "Update image tag to $NEW_TAG [skip ci]"
            git push
            echo "GitOps repository updated with new tag: $NEW_TAG"
          else
            echo "No changes to commit."
          fi